"""empty message

Revision ID: 4dbc9fc682cc
Revises: 787f6a226b5b
Create Date: 2021-04-14 13:18:53.947990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbc9fc682cc'
down_revision = '787f6a226b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_filepath', sa.String(), nullable=True),
    sa.Column('output_filepath', sa.String(), nullable=True),
    sa.Column('consolidated_filepath', sa.String(), nullable=True),
    sa.Column('log_filepath', sa.String(), nullable=True),
    sa.Column('tracker_filepath', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotate_proxy', sa.Boolean(), nullable=True),
    sa.Column('fetch_proxies', sa.Integer(), nullable=True),
    sa.Column('rotating_proxy_page_retry', sa.Integer(), nullable=True),
    sa.Column('no_of_concurrent_request', sa.Integer(), nullable=True),
    sa.Column('download_delay', sa.Integer(), nullable=True),
    sa.Column('download_timeout', sa.Integer(), nullable=True),
    sa.Column('no_of_pg_crawl', sa.Integer(), nullable=True),
    sa.Column('no_of_retry', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    op.drop_table('directory')
    # ### end Alembic commands ###
