"""Add setting model

Revision ID: 613182698147
Revises: 95e135d364f9
Create Date: 2021-01-29 18:01:07.319083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613182698147'
down_revision = '95e135d364f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_filepath', sa.String(), nullable=True),
    sa.Column('output_filepath', sa.String(), nullable=True),
    sa.Column('consolidated_filepath', sa.String(), nullable=True),
    sa.Column('log_filepath', sa.String(), nullable=True),
    sa.Column('no_of_pg_crawl', sa.Integer(), nullable=True),
    sa.Column('no_of_retry', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
