"""empty message

Revision ID: 787f6a226b5b
Revises: 63658b9c6c4d
Create Date: 2021-04-14 13:10:30.719115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787f6a226b5b'
down_revision = '63658b9c6c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory', sa.Column('consolidated_filepath', sa.String(), nullable=True))
    op.add_column('directory', sa.Column('input_filepath', sa.String(), nullable=True))
    op.add_column('directory', sa.Column('log_filepath', sa.String(), nullable=True))
    op.add_column('directory', sa.Column('output_filepath', sa.String(), nullable=True))
    op.add_column('directory', sa.Column('tracker_filepath', sa.String(), nullable=True))

    with op.batch_alter_table('directory') as batch_op:
        batch_op.drop_column('rotating_proxy_page_retry')
        batch_op.drop_column('no_of_concurrent_request')
        batch_op.drop_column('fetch_proxies')
        batch_op.drop_column('download_delay')
        batch_op.drop_column('download_timeout')
        batch_op.drop_column('rotate_proxy')

    with op.batch_alter_table('setting') as batch_op_b:
        batch_op_b.drop_column('tracker_filepath')
        batch_op_b.drop_column('input_filepath')
        batch_op_b.drop_column('consolidated_filepath')
        batch_op_b.drop_column('output_filepath')
        batch_op_b.drop_column('log_filepath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('log_filepath', sa.VARCHAR(), nullable=True))
    op.add_column('setting', sa.Column('output_filepath', sa.VARCHAR(), nullable=True))
    op.add_column('setting', sa.Column('consolidated_filepath', sa.VARCHAR(), nullable=True))
    op.add_column('setting', sa.Column('input_filepath', sa.VARCHAR(), nullable=True))
    op.add_column('setting', sa.Column('tracker_filepath', sa.VARCHAR(), nullable=True))
    op.add_column('directory', sa.Column('rotate_proxy', sa.BOOLEAN(), nullable=True))
    op.add_column('directory', sa.Column('download_timeout', sa.INTEGER(), nullable=True))
    op.add_column('directory', sa.Column('download_delay', sa.INTEGER(), nullable=True))
    op.add_column('directory', sa.Column('fetch_proxies', sa.INTEGER(), nullable=True))
    op.add_column('directory', sa.Column('no_of_concurrent_request', sa.INTEGER(), nullable=True))
    op.add_column('directory', sa.Column('rotating_proxy_page_retry', sa.INTEGER(), nullable=True))
    op.drop_column('directory', 'tracker_filepath')
    op.drop_column('directory', 'output_filepath')
    op.drop_column('directory', 'log_filepath')
    op.drop_column('directory', 'input_filepath')
    op.drop_column('directory', 'consolidated_filepath')
    # ### end Alembic commands ###
