"""add new setting fields

Revision ID: a33fc20e0c4c
Revises: 613182698147
Create Date: 2021-02-11 15:31:46.521075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33fc20e0c4c'
down_revision = '613182698147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('download_delay', sa.Integer(), nullable=True))
    op.add_column('setting', sa.Column('download_timeout', sa.Integer(), nullable=True))
    op.add_column('setting', sa.Column('fetch_proxies', sa.Integer(), nullable=True))
    op.add_column('setting', sa.Column('no_of_concurrent_request', sa.Integer(), nullable=True))
    op.add_column('setting', sa.Column('rotate_proxy', sa.Boolean(), nullable=True))
    op.add_column('setting', sa.Column('rotating_proxy_page_retry', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'rotating_proxy_page_retry')
    op.drop_column('setting', 'rotate_proxy')
    op.drop_column('setting', 'no_of_concurrent_request')
    op.drop_column('setting', 'fetch_proxies')
    op.drop_column('setting', 'download_timeout')
    op.drop_column('setting', 'download_delay')
    # ### end Alembic commands ###
